### ISSUE TITLE
Package the project for PyPi

### ISSUE THREAD

**Issue by tvercaut** [taigw/geodesic_distance#4]
It would be great to be able to simply `pip install` this package. No need to provide pre-built wheels as we can expect interested people would have a c++ compiler.

See e.g. the discussion here:
- https://stackoverflow.com/questions/42656388/how-to-put-a-swig-pybind11-c-project-on-pypi

**Comment by taigw** [comment]
@tvercaut Now users can install this package with `pip install GeodisTK`
