### ISSUE TITLE
Missing one term in the geodesic distance

### ISSUE THREAD

**Issue by John1231983** [taigw/geodesic_distance#5]
In the original paper, the geodesic distance is defined:
![2](https://user-images.githubusercontent.com/24875971/53514622-1e567a00-3a96-11e9-92f1-9ccf52faf3c1.JPG)

while it is defined as below in your paper
![1](https://user-images.githubusercontent.com/24875971/53514663-34643a80-3a96-11e9-8060-00d9fd0f4b08.JPG)

it shows that you are missing the first term in the formular. Is it right? As mentioned in the original paper, the first term is Euclidean distance.

**Comment by taigw** [comment]
@John1231983 (2) can be seen as an extreme version of (1). Here (2) is fully defined based on Geodesic and (1) contains information of Euclidean distance (not purely geodesic). In my code I defined a parameter  lamb which balances the two terms:

`def geodesic_distance_2d(I, S, lamb, iter):

    '''

    get 2d geodesic disntance by raser scanning.

    I: input image

    S: binary image where non-zero pixels are used as seeds

    lamb: weighting betwween 0.0 and 1.0

          if lamb==0.0, return spatial euclidean distance without considering gradient

          if lamb==1.0, the distance is based on gradient only without using spatial distance

    iter: number of iteration for raster scanning.

    '''

    return geodesic_distance.geodesic2d_raster_scan(I,S, lamb, iter)`

**Comment by John1231983** [comment]
Thanks for your reply. But I did not find any lamb term in your equation (2). I mean if  lamb is 0.5, then two terms contributes equally and it should be appear in the equation

**Comment by taigw** [comment]
equation (2) is the case of lamb == 1.0

**Comment by John1231983** [comment]
@taigw : It is clear now. So, can your code can produce the results likes eq. (1) in case of lamb = 0.5? It means I want to consider the first term also.

**Comment by taigw** [comment]
Yes, you can set lamb to 0.5 to obtain a mixture of the two terms. I have updated the 2D example as you can see in the readme file.
